/**
 * Don't change this file manually it is generated by the ./bin/extract_translation.cjs script
 * to satisfy Nextcloud's bot as it does not know how to read .svelte files.
 */
 
// @ts-ignore
const { t } = window;

const label0 = t('thesearchpage', 'All providers');
const label1 = t('thesearchpage', 'Back');
const label2 = t('thesearchpage', 'Clear current query');
const label3 = t('thesearchpage', 'Click to change providers');
const label4 = t('thesearchpage', 'Filters');
const label5 = t('thesearchpage', 'Load more...');
const label6 = t('thesearchpage', 'Loading...');
const label7 = t('thesearchpage', 'No results');
const label8 = t('thesearchpage', 'Search');
const label9 = t('thesearchpage', 'Search Page');
const label10 = t('thesearchpage', 'See all providers');
const label11 = t('thesearchpage', 'See only results for this provider');
const label12 = t('thesearchpage', 'Show only');
const label13 = t('thesearchpage', 'There was an error loading the providers.');
console.log(label0);
console.log(label1);
console.log(label2);
console.log(label3);
console.log(label4);
console.log(label5);
console.log(label6);
console.log(label7);
console.log(label8);
console.log(label9);
console.log(label10);
console.log(label11);
console.log(label12);
console.log(label13);
