OC.L10N.register(
    "thesearchpage",
    {
    "Provides a proper search page" : "Обеспечивает правильную страницу поиска",
    "🔎 A Search Page for your Nextcloud instance\n\n- [Changelog](https://raw.githubusercontent.com/callmemagnus/nextcloud-searchpage/main/CHANGELOG.md)\n- [Help translate this application](https://app.transifex.com/nextcloud/nextcloud/thesearchpage/)\n\nIt works like the existing search widget, uses the same sources to query BUT\ndisplays the results in a more readable and browsable fashion.\n\nThe content of the results depends on the other applications installed on\nyour Nextcloud instance. Every Nextcloud application can become a search\nprovider and get its results displayed by this application.\n\nOut of the Nextcloud box, you usually get the following providers:\n\n- Apps -- searches for match for in installed application names\n- Files -- searches on path and filename\n- Tags\n- Comments\n- Settings\n\nBecause of its design, the results depend on the implementation of the providers\nin respective application.\n\nKnown issues with other applications:\n\n- users -- [by design(?), it always returns an empty array](https://github.com/nextcloud/server/issues/41274) (it is hidden/disabled in this application)\n- fulltextsearch -- does not seem to AND the query terms, OR is usually less relevant\n- news -- does not provide a direct link to a feed item.\n\n\nDon't hesitate to leave a comment here or a rating!" : "🔎 Страница поиска для вашего экземпляра Nextcloud\n\n- [Список изменений](https://raw.githubusercontent.com/callmemagnus/nextcloud-searchpage/main/CHANGELOG.md)\n- [Помогите перевести это приложение](https://app.transifex.com/nextcloud/nextcloud/thesearchpage/)\n\nОн работает как существующий виджет поиска, использует те же источники для запроса, НО\nотображает результаты в более читабельной и удобной для просмотра форме.\n\nСодержимое результатов зависит от других приложений, установленных на вашем экземпляре Nextcloud. Каждое приложение Nextcloud может стать поставщиком поиска и получать свои результаты, отображаемые этим приложением.\n\nИз коробки Nextcloud вы обычно получаете следующие поставщики:\n\n- Приложения — поиск совпадений в именах установленных приложений\n- Файлы — поиск по пути и имени файла\n- Теги\n- Комментарии\n- Настройки\n\nИз-за своей конструкции результаты зависят от реализации поставщиков\nв соответствующем приложении.\n\nИзвестные проблемы с другими приложениями:\n\n- пользователи — [по замыслу(?) всегда возвращает пустой массив](https://github.com/nextcloud/server/issues/41274) (он скрыт/отключен в этом приложении)\n- полнотекстовый поиск — похоже, не выполняет операцию AND с условиями запроса, ИЛИ обычно менее релевантен\n- новости — не предоставляет прямую ссылку на элемент ленты.\n\nНе стесняйтесь оставлять здесь комментарии или оценки!",
    "Back" : "Назад",
    "Filters" : "Фильтры",
    "Global settings" : "Общие настройки",
    "Group settings" : "Настройки группы",
    "Loading…" : "Загрузка…",
    "No results" : "Нет результатов",
    "Saved" : "Сохранённые",
    "Search" : "Поиск",
    "Loading..." : "Загрузка...",
    "Note:" : "Примечание:",
    "Provider" : "Поставщик услуги",
    "Save" : "Сохранить",
    "Saving..." : "Сохранение…"
},
"nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || (n%10>=5 && n%10<=9) || (n%100>=11 && n%100<=14)? 2 : 3);");
