/**
 * Don't change this file manually it is generated by the ./bin/extract_translation.cjs script
 * to satisfy Nextcloud's bot as it does not know how to read .svelte files.
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment 
// @ts-ignore
const { t } = window;

const label0 = t('thesearchpage', 'All providers');
const label1 = t('thesearchpage', 'Back');
const label2 = t('thesearchpage', 'Clear current query');
const label3 = t('thesearchpage', 'Click to change providers');
const label4 = t('thesearchpage', 'Filters');
const label5 = t('thesearchpage', 'Global settings');
const label6 = t('thesearchpage', 'Group settings');
const label7 = t('thesearchpage', 'If a user is part of multiple groups, the union of the groups configurations will be applied.');
const label8 = t('thesearchpage', 'Load more…');
const label9 = t('thesearchpage', 'Loading…');
const label10 = t('thesearchpage', 'No results');
const label11 = t('thesearchpage', 'Saved');
const label12 = t('thesearchpage', 'Search');
const label13 = t('thesearchpage', 'Search Page');
const label14 = t('thesearchpage', 'Security is applied by the search providers.');
const label15 = t('thesearchpage', 'See all providers');
const label16 = t('thesearchpage', 'See only results for this provider');
const label17 = t('thesearchpage', 'Select the providers that will be available to all the users:');
const label18 = t('thesearchpage', 'Select the providers that will be available to the users in group "{group}":');
const label19 = t('thesearchpage', 'Show only');
const label20 = t('thesearchpage', 'The Search Page');
const label21 = t('thesearchpage', 'There was an error loading the providers.');
const label22 = t('thesearchpage', 'This is not a security configuration.');
const label23 = t('thesearchpage', 'Unable to save');
console.log(label0);
console.log(label1);
console.log(label2);
console.log(label3);
console.log(label4);
console.log(label5);
console.log(label6);
console.log(label7);
console.log(label8);
console.log(label9);
console.log(label10);
console.log(label11);
console.log(label12);
console.log(label13);
console.log(label14);
console.log(label15);
console.log(label16);
console.log(label17);
console.log(label18);
console.log(label19);
console.log(label20);
console.log(label21);
console.log(label22);
console.log(label23);
