
// SPDX-FileCopyrightText: Magnus Anderssen <magnus@magooweb.com>
// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * Don't change this file manually it is generated by the ./bin/extract_translation.cjs script
 * to satisfy Nextcloud's bot as it does not know how to read .svelte files.
 */
 
// @ts-ignore
const { t } = window;

const label0 = t('thesearchpage', 'All providers');
const label1 = t('thesearchpage', 'Back');
const label2 = t('thesearchpage', 'Clear current query');
const label3 = t('thesearchpage', 'Click to change providers');
const label4 = t('thesearchpage', 'Configure search provider visibility per group.');
const label5 = t('thesearchpage', 'Configure the number of search results to display for each provider (5-100).');
const label6 = t('thesearchpage', 'Default configuration');
const label7 = t('thesearchpage', 'Enable provider restrictions');
const label8 = t('thesearchpage', 'Enable {providerName} for {groupName}');
const label9 = t('thesearchpage', 'Error loading settings: {error}');
const label10 = t('thesearchpage', 'Error saving settings');
const label11 = t('thesearchpage', 'Filters');
const label12 = t('thesearchpage', 'Higher values may result in slower response times, especially for providers with large datasets.');
const label13 = t('thesearchpage', 'Load more...');
const label14 = t('thesearchpage', 'Loading settings...');
const label15 = t('thesearchpage', 'Loading...');
const label16 = t('thesearchpage', 'New search providers detected');
const label17 = t('thesearchpage', 'No results');
const label18 = t('thesearchpage', 'Not available to any group');
const label19 = t('thesearchpage', 'Note:');
const label20 = t('thesearchpage', 'Number of results for {providerName}');
const label21 = t('thesearchpage', 'Please review the visibility settings for these providers below and save your changes.');
const label22 = t('thesearchpage', 'Provider');
const label23 = t('thesearchpage', 'Results per search');
const label24 = t('thesearchpage', 'Save');
const label25 = t('thesearchpage', 'Saving...');
const label26 = t('thesearchpage', 'Search');
const label27 = t('thesearchpage', 'Search Page');
const label28 = t('thesearchpage', 'Search results per provider');
const label29 = t('thesearchpage', 'See all providers');
const label30 = t('thesearchpage', 'See only results for this provider');
const label31 = t('thesearchpage', 'Settings saved successfully');
const label32 = t('thesearchpage', 'Show only');
const label33 = t('thesearchpage', 'The Search Page settings');
const label34 = t('thesearchpage', 'The following provider(s) were not available when settings were last saved: {providers}');
const label35 = t('thesearchpage', 'There was an error loading the providers.');
const label36 = t('thesearchpage', 'User group');
const label37 = t('thesearchpage', 'When enabled, you can control which search providers are visible to specific user groups. By default, all providers are enabled for all groups.');
console.log(label0);
console.log(label1);
console.log(label2);
console.log(label3);
console.log(label4);
console.log(label5);
console.log(label6);
console.log(label7);
console.log(label8);
console.log(label9);
console.log(label10);
console.log(label11);
console.log(label12);
console.log(label13);
console.log(label14);
console.log(label15);
console.log(label16);
console.log(label17);
console.log(label18);
console.log(label19);
console.log(label20);
console.log(label21);
console.log(label22);
console.log(label23);
console.log(label24);
console.log(label25);
console.log(label26);
console.log(label27);
console.log(label28);
console.log(label29);
console.log(label30);
console.log(label31);
console.log(label32);
console.log(label33);
console.log(label34);
console.log(label35);
console.log(label36);
console.log(label37);
