# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization
# SPDX-FileCopyrightText: Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Lint (info.xml)

on:
  pull_request:
  push:
    branches:
      - main
      - stable*

jobs:
  xml-linters:
    runs-on: ubuntu-latest

    name: info.xml lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download schema
        run: wget https://apps.nextcloud.com/schema/apps/info.xsd

      - name: Lint info.xml
        uses: ChristophWurst/xmllint-action@v1.2.1
        with:
          xml-file: ./appinfo/info.xml
          xml-schema-file: ./info.xsd
